<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>



<div class="page-header">
    <h1>
        สร้างกิจกรรม
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/createActivity",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldActivityname" class="col-sm-2 control-label">ชื่อกิจกรรม</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["ActivityName", "size" => 30, "class" => "form-control", "id" => "fieldActivityname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDetail" class="col-sm-2 control-label">รายละเอียด</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textarea(["Detail", "size" => 30, "class" => "form-control", "id" => "fieldDetail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStartdate" class="col-sm-2 control-label">วันเริ่มต้นกิจกรรม</label>
    <div class="col-sm-4">
        <?php echo $this->tag->dateField(["nStartdate", "size" => 30, "class" => "form-control", "id" => "nStartdate"]) ?>
        <!-- <input type="date" name="nStartdatee" id="nStartdate"><br> -->
    </div>
</div>

<div class="form-group">
    <label for="fieldEnddate" class="col-sm-2 control-label">วันสุดท้ายกิจกรรม</label>
    <div class="col-sm-4">
        <?php echo $this->tag->dateField(["nEnddate", "size" => 30, "class" => "form-control", "id" => "nEnddate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYearstd" class="col-sm-2 control-label">ชั้นปีนักศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["YearSTD", "size" => 30, "class" => "form-control", "id" => "fieldYearstd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLocaionIdlocaion" class="col-sm-2 control-label">สถานที่</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["Locaion_idLocaion", "type" => "number", "class" => "form-control", "id" => "fieldLocaionIdlocaion"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldTypeIdtype" class="col-sm-2 control-label">ประเภภทกิจกรรม</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["Type_idType", "type" => "number", "class" => "form-control", "id" => "fieldTypeIdtype"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYearofeducationSemeter" class="col-sm-2 control-label">เทอม</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["YearOfEducation_semeter", "type" => "number", "class" => "form-control", "id" => "fieldYearofeducationSemeter"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYearofeducationYear" class="col-sm-2 control-label">ปีการศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["YearOfEducation_Year", "type" => "number", "class" => "form-control", "id" => "fieldYearofeducationYear"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPicture" class="col-sm-2 control-label">รูปภาพ</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["picture", "size" => 30, "class" => "form-control", "id" => "fieldPicture"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
        <?php echo $this->tag->submitButton(["สร้าง", "class" => "btn btn-default"]) ?>
    </div>
</div>




<?php echo $this->tag->endForm(); ?>

<script>

    var dtToday = new Date();
    
    var month = dtToday.getMonth() + 1;
    var day = dtToday.getDate();
    var year = dtToday.getFullYear();
    if(month < 10)
        month = '0' + month.toString();
    if(day < 10)
        day = '0' + day.toString();
    
    var minDate = year + '-' + month + '-' + day;

    $('#nStartdate').attr('min', minDate);
    $('#nEnddate').attr('min', minDate);
   


</script>