<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>



<div class="page-header">
    <h1>
        เพิ่มข้อมูลนักศึกษา
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "admin/createSTD",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdstudent" class="col-sm-2 control-label">รหัศนักศึกษา</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNametitle" class="col-sm-2 control-label">คำนำหน้า</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["NameTitle", "size" => 30, "class" => "form-control", "id" => "fieldNametitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">ชื่อ</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">นามสกุล</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">ชั้นปี</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["Year", "type" => "number", "class" => "form-control", "id" => "fieldYear"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
        <?php echo $this->tag->submitButton(["บันทึก", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
