  <?php echo $this->flashSession->output() ?>
 <div class="container">
       
        <div class="page-header">
            <h1>บันทึกการเข้าร่วมกิจกรรม</h1>
        </div>


        <div class="row">
            <table class="table table-bordered">
                <thead >
                    <tr>
                        <th>No.</th>
                        <th></th>
                        <th>ชื่อกิจกรรม</th>
                        <th></th>
                        
                        
                        
                    </tr>
                </thead>
                <tbody>
                <?php $i=1;foreach ($page->items as $activity): ?>
                    <tr>
                        <td class="col-md-1"><?php echo $i; $i++;?></td>
                        <td class="col-md-2">
                            <img class="img-responsive" src="<?php echo $activity->picture;?>"
                            alt="" style="width:700px;height:100px";>

                        </td>
                        <td class="col-md-6"><?php echo $activity->ActivityName ?></td>
                        <td class="col-md-2" align="center"><?php echo $this->tag->linkTo(["admin/saveHistory/" . $activity->idActivity, '<img src="../public/img/edit.png">']); ?></td>
                       
                        
                    
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-1">
                <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                    <?php echo $page->current, "/", $page->total_pages ?>
                </p>
            </div>
            <div class="col-sm-11">
                <nav>
                    <ul class="pagination">
                        <li><?php echo $this->tag->linkTo("home/searchAc", "หน้าแรก") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAc?page=" . $page->before, "หน้าก่อนหน้า") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAc?page=" . $page->next, "หน้าต่อไป") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAC?page=" . $page->last, "หน้าสุดท้าย") ?></li>
                    </ul>
                </nav>
            </div>
        </div>
</div>