<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>รายชื่อนักศึกษา</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>รหัสนักศึกษา</th>
                <th>คำนำหน้า</th>
                <th>ชื่อ</th>
                <th>นามสกุล</th>
                <th>ชั้นปี</th>
                <th></th>
                <th></th>
               
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $student): 
                if($student->active == 1){
        ?>
            <tr>
                <td><?php echo $student->idStudent ?></td>
                <td><?php echo $student->NameTitle ?></td>
                <td><?php echo $student->FirstName ?></td>
                <td><?php echo $student->LastName ?></td>
                <td><?php echo $student->Year ?></td>
                <td><?php echo $this->tag->linkTo(["admin/editSTD/" . $student->idStudent, '<img src="../public/img/edit.png">']); ?></td>
                <td><?php echo $this->tag->linkTo(["admin/deleteSTD/" . $student->idStudent, '<img src="../public/img/bin.png">']); ?></td>
            </tr>
        <?php }endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("admin/searchSTD", "หน้าแรก") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchSTD?page=" . $page->before, "หน้าก่อนหน้า") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchSTD?page=" . $page->next, "หน้าต่อไป") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchSTD?page=" . $page->last, "หน้าสุดท้าย") ?></li>
            </ul>
        </nav>
    </div>
</div>
