<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<div class="page-header">
    <h1>อาจารย์</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ชื่อผู้ใช้</th>
                <th>รหัสผ่าน</th>
                <th>คำนำหน้า</th>
                <th>ชื่อ</th>
                <th>นามสกุล</th>
                <th>Admin</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $teacher): ?>
            <tr>
                <td><?php echo $teacher->username ?></td>
                <td><?php echo $teacher->password ?></td>
                <td><?php echo $teacher->NameTitle ?></td>
                <td><?php echo $teacher->FirstName ?></td>
                <td><?php echo $teacher->LastName ?></td>
                <td>
                    <?php $state = $teacher->admin;
                        if($state== 1){
                            echo "admin";
                        }else{
                            echo "Is not admin";
                        }
                    ?>
                </td>

                <td><?php echo $this->tag->linkTo(["admin/editTeacher/" . $teacher->idTeacher, '<img src="../public/img/edit.png">']); ?></td>
               
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("admin/searchTeacher", "หน้าแรก") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchTeacher?page=" . $page->before, "หน้าก่อนหน้า") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchTeacher?page=" . $page->next, "หน้าต่อไป") ?></li>
                <li><?php echo $this->tag->linkTo("admin/searchTeacher?page=" . $page->last, "หน้าสุดท้าย") ?></li>
            </ul>
        </nav>
    </div>
</div>
