<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>



<div class="page-header">
    <h1>กิจกรรม</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ชื่อกิจกรรม</th>
            <th>รายละเอียด</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $activity): ?>
            <tr>
                <td class="col-md-3"><?php echo $activity->ActivityName ?></td>
                <td class="col-md-8"><?php echo $activity->Detail ?></td>           
                <td align="center"><?php echo $this->tag->linkTo(["admin/editActivity/" . $activity->idActivity,'<img src="../public/img/edit.png">']); ?></td> 
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("activity/search", "หร้าแรก") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->before, "หน้าก่อนหน้า") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->next, "หน้าต่อไป") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->last, "หน้าสุดท้าย") ?></li>
            </ul>
        </nav>
    </div>
</div>
