
    <?php echo $this->flashSession->output() ?>
    <div class="container">
        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><font face="Arial" color="blue">กิจกรรมหลักสูตรวิศวกรรมซอฟต์แวร์</font>
                    <!--<small>Secondary Text</small>-->
                </h1>
            </div>
        </div>
        <!-- /.row ---->
                    <?php
                      foreach($page->items as $row):
                    ?>
                       <div class="row-md">
                          <div class="col-sm-6 col-md-4">
                              <div class="thumbnail">
                                <a href="#">
                                  <img class="img-responsive" src="<?php echo $row->picture;?>"
                                  alt="" style="width:350px;height:250px";>
                                </a>
                                <h3>
                                  <?php echo $this->tag->linkTo(["home/detail/".$row->idActivity,$row->ActivityName,]) ?>
                                </h3>
                                <p><?php echo $row->Detail;?><?php echo "<br><br>" ;?></p>
                              </div>
                          </div>
                      </div>
                    <?php
                    endforeach;
                   ?>
            
 <div class="row">
        <div class="col-sm-1">
          <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
          </p>
        </div>

        <div class="col-sm-11">
            <nav>
              <ul class="pagination">
                <li><?php echo $this->tag->linkTo("home/index", "หน้าแรก") ?></li>
                <li><?php echo $this->tag->linkTo("home/index?page=" . $page->before,"หน้าก่อนหน้า") ?></li>
                <li><?php echo $this->tag->linkTo("home/index?page=" . $page->next, "หน้าต่อไป") ?></li>
                <li><?php echo $this->tag->linkTo("home/index?page=" . $page->last, "หน้าสุดท้าย") ?></li>
              </ul>
            </nav>
        </div>
    </div>
</div>
      

    <!-- /.container -->
