 <div class="container">
 

        <div class="page-header">
            <h1>ผลการค้นหา</h1>
        </div>


        <div class="row">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th></th>
                        <th>ชื่อกิจกรรม</th>
                        <th>รายละเอียด</th>
                        <th>วันเริ่มต้น</th>
                        <th>วันสุดท้าย</th>
                        
                        
                    </tr>
                </thead>
                <tbody>
                <?php $i=1;foreach ($page->items as $activity): ?>
                    <tr>
                        <td><?php echo $i; $i++;?></td>
                        <td class="col-md-2">
                            <img class="img-responsive" src="<?php echo $activity->picture;?>"
                            alt="" style="width:700px;height:100px";>

                        </td>
                        <td class="col-md-2"><?php echo $this->tag->linkTo(["home/detail/".$activity->idActivity,$activity->ActivityName,]) ?></td>
                        <td><?php echo $activity->Detail ?></td>
                        <td><?php echo date('d/m/Y',strtotime($activity->StartDate));?></td>
                        <td><?php echo date('d/m/Y',strtotime($activity->EndDate)); ?></td>
                        
                    
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-1">
                <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                    <?php echo $page->current, "/", $page->total_pages ?>
                </p>
            </div>
            <div class="col-sm-11">
                <nav>
                    <ul class="pagination">
                        <li><?php echo $this->tag->linkTo("home/searchAc", "First") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAc?page=" . $page->before, "Previous") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAc?page=" . $page->next, "Next") ?></li>
                        <li><?php echo $this->tag->linkTo("home/searchAC?page=" . $page->last, "Last") ?></li>
                    </ul>
                </nav>
            </div>
        </div>
</div>