<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search detailactivity
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["detailactivity/new", "Create detailactivity"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "detailactivity/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIddetailactivity" class="col-sm-2 control-label">IdDetailactivity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDetailactivity", "type" => "number", "class" => "form-control", "id" => "fieldIddetailactivity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdstudent" class="col-sm-2 control-label">IdStudent</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idStudent", "size" => 30, "class" => "form-control", "id" => "fieldIdstudent"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdactivity" class="col-sm-2 control-label">IdActivity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idActivity", "type" => "number", "class" => "form-control", "id" => "fieldIdactivity"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
