<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
 			<a href="http://localhost/phalcon_Activity/admin/index"><img src="<?=$this->url->get('public/img/nav/home.png')?>"></a>
 	</div>

 		<ul class="nav navbar-nav">
 				<li>
            <a href="#" data-toggle="modal" data-target="#searchAc">ค้นหากิจกรรม</a>
        </li>
        <li>
            <a href="#" data-toggle="modal" data-target="#searchHistory">ประวัติกิจกรรมนักศึกษา</a>
        </li>
        <li>
           <a href="#" data-toggle="modal" data-target="#saveHistory">บันทึกการเข้าร่วมกิจกรรม</a>
        </li>
 				<li class="dropdown">
          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">กิจกรรม<span class="caret"></span></a>
          			<ul class="dropdown-menu">
            			<li><?php echo $this->tag->linkTo(["admin/newActivity", "สร้างกิจกรรม"]); ?></li>
			            <li><?php echo $this->tag->linkTo(["admin/searchActivity", "แก้ไขข้อมูลกิจกรรม"]); ?></li>
 					</ul>
 				</li>
        <?php 
            $status = $this->session->get("status");
            if($status == 1){?>
         <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">อาจารย์<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><?php echo $this->tag->linkTo(["admin/newTeacher", "เพิ่มข้อมูลอาจารย์"]); ?></li>
                  <li><?php echo $this->tag->linkTo(["admin/searchTeacher", "แก้ไขข้อมูลอาจารย์"]); ?></li>
          </ul>
        </li>
        <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">นักศึกษา<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><?php echo $this->tag->linkTo(["admin/newSTD", "เพิ่มข้อมูลนักศึกษา"]); ?></li>
                  <li><?php echo $this->tag->linkTo(["admin/searchSTD", "แก้ไขข้อมูลนักศึกษา"]); ?></li>
          </ul>
        </li>
        <?php }?>
 		</ul>


    <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><img src="<?=$this->url->get('public/img/user.jpg')?>"></a>
            <ul class="dropdown-menu">
                    <?php $user = $this->session->get("username");?>
                   
                    <li><?php echo $this->tag->linkTo(["admin/index", $user]); ?></li>
                    <li><?php echo $this->tag->linkTo(["user/logout", "ออกจากระบบ"]); ?></li>
            </ul>
 		     </li>
		</ul>
	</div>
</nav>

      <div class="modal fade" id="searchAc" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <center><h4 class="modal-title">ค้นหากิจกรรม</h4></center>
                </div>
                <div class="modal-body">
                <?php
                  echo $this->tag->form(
                    [
                      "admin/searchAc",
                      "autocomplete" => "off",
                      "class" => "form-horizontal"
                    ]
                  );
                ?>
                  <div class="form-group">
                       <div class="input-group">
                          <span class="input-group-addon">
                              <i class="glyphicon glyphicon-user"></i>
                          </span> 
                               <?php echo $this->tag->textField([
                                  "ActivityName", 
                                  "size" => 10, 
                                  "class" => "form-control", 
                                  "placeholder" => "ชื่อกิจกรรม",
                                  "id" =>"fieldActivityname" ,
                                  'autofocus' => true,]) 
                              ?> 
                        </div>
                  </div>
                  <div class="form-group">
                      <?php echo $this->tag->submitButton([
                          "ค้นหา", 
                          "class" => "btn btn-lg btn-primary btn-block"
                      ]) ?>
                  </div>

                   <?php echo $this->tag->endForm(); ?>
                </div>

               

                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
                </div>
              </div>
              
           </div>
        </div>


        <div class="modal fade" id="searchHistory" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <center><h4 class="modal-title">ประวัติการเข้าร่วม</h4></center>
                </div>
                <div class="modal-body">
                <?php
                  echo $this->tag->form(
                    [
                      "admin/searchHistory",
                      "autocomplete" => "off",
                      "class" => "form-horizontal"
                    ]
                  );
                ?>
                  <div class="form-group">
                       <div class="input-group">
                          <span class="input-group-addon">
                              <i class="glyphicon glyphicon-user"></i>
                          </span> 
                              <?php echo $this->tag->textField([
                                  "idStudent", 
                                  "size" => 10, 
                                  "class" => "form-control", 
                                  "placeholder" => "รหัสนักศึกษา",
                                  "id" =>"fieldName" ,
                                  'autofocus' => true,]) 
                              ?>
                        </div>
                  </div>
                  <div class="form-group">
                      <?php echo $this->tag->submitButton([
                          "ค้นหา", 
                          "class" => "btn btn-lg btn-primary btn-block"
                      ]) ?>
                  </div>

                   <?php echo $this->tag->endForm(); ?>
                </div>

               

                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
                </div>
              </div>
              
           </div>
        </div>

        <div class="modal fade" id="saveHistory" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <center><h4 class="modal-title">ค้นหากิจกรรม</h4></center>
                </div>
                <div class="modal-body">
                <?php
                  echo $this->tag->form(
                    [
                      "admin/saveAc",
                      "autocomplete" => "off",
                      "class" => "form-horizontal"
                    ]
                  );
                ?>
                  <div class="form-group">
                       <div class="input-group">
                          <span class="input-group-addon">
                              <i class="glyphicon glyphicon-user"></i>
                          </span> 
                               <?php echo $this->tag->textField([
                                  "ActivityName", 
                                  "size" => 10, 
                                  "class" => "form-control", 
                                  "placeholder" => "ชื่อกิจกรรม",
                                  "id" =>"fieldActivityname" ,
                                  'autofocus' => true,]) 
                              ?> 
                        </div>
                  </div>
                  <div class="form-group">
                      <?php echo $this->tag->submitButton([
                          "ค้นหา", 
                          "class" => "btn btn-lg btn-primary btn-block"
                      ]) ?>
                  </div>

                   <?php echo $this->tag->endForm(); ?>
                </div>

               

                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
                </div>
              </div>
              
           </div>
        </div>





<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>