<nav class="navbar navbar-default navbar-fixed-top"  >
    <div class="container-fluid">
    <div class="navbar-header">
 			<a href="http://localhost/phalcon_Activity/home/index"><img src="<?=$this->url->get('public/img/nav/home.png')?>"></a>


 	</div>
 		<ul class="nav navbar-nav">
 				<li>
 					<a href="#" data-toggle="modal" data-target="#searchAc">ค้นหากิจกรรม</a>
 				</li>
 				<li>
 				<a href="#" data-toggle="modal" data-target="#searchHistory">ประวัติกิจกรรมนักศึกษา</a>
 					
 				</li>
 		</ul>


        <ul class="nav navbar-nav navbar-right">
				<li class="fh5co-special"><button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#login">เข้าสู่ระบบ</button></li>
		</ul>
	</div>
</nav>

				
				<div class="modal fade" id="login" role="dialog">
				    <div class="modal-dialog">
				    
				      <!-- Modal content-->
				      <div class="modal-content">
				        <div class="modal-header">
				          <button type="button" class="close" data-dismiss="modal">&times;</button>
				          <center><h4 class="modal-title">ลงชื่อเข้าสู่ระบบ</h4></center>
				        </div>
				        <div class="modal-body">
				        <?php
				          echo $this->tag->form(
				            [
				              "User/checkLogin",
				              "autocomplete" => "off",
				              "class" => "form-horizontal"
				            ]
				          );
				        ?>
				          <div class="form-group">
				               <div class="input-group">
				                  <span class="input-group-addon">
				                      <i class="glyphicon glyphicon-user"></i>
				                  </span> 
				                      <?php echo $this->tag->textField([
				                          "login", 
				                          "size" => 10, 
				                          "class" => "form-control", 
				                          "placeholder" => "ชื่อผู้ใช้",
				                          "id" =>"fieldName" ,
				                          'autofocus' => true,]) 
				                      ?>
				                </div>
				          </div>
				          <div class="form-group">
				                <div class="input-group">
				                  <span class="input-group-addon">
				                      <i class="glyphicon glyphicon-lock"></i>
				                  </span>
				                       <?php echo $this->tag->passwordField([
				                          "password", 
				                          "size" => 10, 
				                          "class" => "form-control", 
				                          "placeholder" => "รหัสผ่าน",
				                          "id" =>"fieldName" ,]) 
				                      ?>
				                </div>
				          </div>
				          <div class="form-group">
				              <?php echo $this->tag->submitButton([
				                  "เข้าสู่ระบบ", 
				                  "class" => "btn btn-lg btn-primary btn-block"
				              ]) ?>
				          </div>

				           <?php echo $this->tag->endForm(); ?>
				        </div>

				       

				        <div class="modal-footer">
				          <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
				        </div>
				      </div>
				      
				    </div>
				  </div>


				
				  	<div class="modal fade" id="searchAc" role="dialog">
				    <div class="modal-dialog">
				    
				      <!-- Modal content-->
				      <div class="modal-content">
				        <div class="modal-header">
				          <button type="button" class="close" data-dismiss="modal">&times;</button>
				          <center><h4 class="modal-title">ค้นหากิจกรรม</h4></center>
				        </div>
				        <div class="modal-body">
				        <?php
				          echo $this->tag->form(
				            [
				              "home/searchAc",
				              "autocomplete" => "off",
				              "class" => "form-horizontal"
				            ]
				          );
				        ?>
				          <div class="form-group">
				               <div class="input-group">
				                  <span class="input-group-addon">
				                      <i class="glyphicon glyphicon-user"></i>
				                  </span> 
				                       <?php echo $this->tag->textField([
				                          "ActivityName", 
				                          "size" => 10, 
				                          "class" => "form-control", 
				                          "placeholder" => "ชื่อกิจกรรม",
				                          "id" =>"fieldActivityname" ,
				                          'autofocus' => true,]) 
				                      ?> 
				                </div>
				          </div>
				          <div class="form-group">
				              <?php echo $this->tag->submitButton([
				                  "ค้นหา", 
				                  "class" => "btn btn-lg btn-primary btn-block"
				              ]) ?>
				          </div>

				           <?php echo $this->tag->endForm(); ?>
				        </div>

				       

				        <div class="modal-footer">
				          <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
				        </div>
				      </div>
				      
				   </div>
				</div>







				<div class="modal fade" id="searchHistory" role="dialog">
				    <div class="modal-dialog">
				    
				      <!-- Modal content-->
				      <div class="modal-content">
				        <div class="modal-header">
				          <button type="button" class="close" data-dismiss="modal">&times;</button>
				          <center><h4 class="modal-title">ประวัติการเข้าร่วม</h4></center>
				        </div>
				        <div class="modal-body">
				        <?php
				          echo $this->tag->form(
				            [
				              "home/searchHistory",
				              "autocomplete" => "off",
				              "class" => "form-horizontal"
				            ]
				          );
				        ?>
				          <div class="form-group">
				               <div class="input-group">
				                  <span class="input-group-addon">
				                      <i class="glyphicon glyphicon-user"></i>
				                  </span> 
				                      <?php echo $this->tag->textField([
				                          "idStudent", 
				                          "size" => 10, 
				                          "class" => "form-control", 
				                          "placeholder" => "รหัสนักศึกษา",
				                          "id" =>"fieldName" ,
				                          'autofocus' => true,]) 
				                      ?>
				                </div>
				          </div>
				          <div class="form-group">
				              <?php echo $this->tag->submitButton([
				                  "ค้นหา", 
				                  "class" => "btn btn-lg btn-primary btn-block"
				              ]) ?>
				          </div>

				           <?php echo $this->tag->endForm(); ?>
				        </div>

				       

				        <div class="modal-footer">
				          <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
				        </div>
				      </div>
				      
				   </div>
				</div>
          
    </div>
</nav>

<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>